apiVersion: batch/v1
kind: Job
metadata:
  name: create-table
  namespace: dynamodb
spec:
  template:
    spec:
      containers:
      - name: create-table
        image: amazon/aws-cli
        command:
        - sh
        - -c
        - |
          export AWS_ACCESS_KEY_ID=local AWS_SECRET_ACCESS_KEY=local
          aws dynamodb create-table \
            --table-name livingexpense \
            --attribute-definitions AttributeName=username,AttributeType=S AttributeName=date_name,AttributeType=S \
            --key-schema AttributeName=username,KeyType=HASH AttributeName=date_name,KeyType=RANGE \
            --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
            --endpoint-url http://dynamodb-svc \
            --region ap-south-1
      restartPolicy: Never