apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dynamodb
  name: dynamodb
  namespace: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
      - image: amazon/dynamodb-local:latest
        name: dynamodb
        args: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-svc
  namespace: dynamodb
spec:
  selector:
    app: dynamodb
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
