apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas | default 2 }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount | default "default" }}
      containers:
      - image: nhphat1997/expenselogger-api:latest
        imagePullPolicy: IfNotPresent
        name: expenselogger-api
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-config
      # probe/readiness/liveness
      # resources
      restartPolicy: Always
