version = 0.1

[dev.global.parameters]
stack_name = "expense-tracker"

[dev.build.parameters]
cached = false
parallel = true

[dev.deploy.parameters]
capabilities = ["CAPABILITY_IAM"]
confirm_changeset = true
resolve_s3 = true
s3_prefix = "expense-tracker"
